### ISSUE TITLE
instant crash on windows 10

### ISSUE THREAD

**Issue by emanuelect** [zZeck/RaymanArenaPatch#1]
I tried the fix on windows 10 and windows 7 on virtual machine. On windows 7 when starting rayman arena the network selection pops up, but on windows 10 it opens for a few moments and then closes immediately.

**Comment by emanuelect** [comment]
I solved it, disabled vmware networks and it started. The game still won't let me host a game though. When I press the create button, the game freezes.

**Comment by zZeck** [comment]
Hey thanks for making an issue! What version of the exe do you have? Resolution patch? Can you post an image of what the adapter selection looks like when it does work?

**Comment by zZeck** [comment]
Do you have procexp? The game SHOULD bind to 41000 and a couple other random ports right after you pass the character selection screen if the patch is working. You can see that in the TCP/IP tab of procexp for the process.

Is windows firewell set to allow R_Arena.exe on private or public networks?

![winProcArena](https://user-images.githubusercontent.com/18518874/129455432-37f08c6c-8c1d-490b-8a05-1679ca7a7998.png)
![sessionSelect](https://user-images.githubusercontent.com/18518874/129455433-b3d6dba6-c7c1-472f-9b0c-afb3a3d971ea.png)

I use DXWnd to run the game in windowed mode during troubleshooting and development.

**Comment by emanuelect** [comment]
![arena online](https://user-images.githubusercontent.com/43710721/129460052-60377b1c-0f05-4cc1-bdb8-fd898a511797.PNG)

The exe is the original one from the Rayman Arena cd, i just modified the firewall right now adding public network too. I won't be home until Monday, but in the home router I already had the port set. I'm using another router right now, so I can't open the port in this one. The startup crash also occurred with the usb cable connected to the android with USB Tethering that I used to connect to the network in this other router.

**Comment by zZeck** [comment]
Hmm. I'm guessing there is something I'm not handling correctly with the network adapters.

Does it work when you just have Ethernet and Hamachi?

[Process Explorer (procexp)](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) can show you if the process grabs 41000.

I do not think the router config could impact this.

Would you be willing to try a build that logs some trace information to a file, and send me the results, if we can't get this figured out by other means?

**Comment by emanuelect** [comment]
![](https://cdn.discordapp.com/attachments/334474004263862273/876383864606576710/unknown.png)

I just tried with the lan cable connected, no port appeared in the program. Anyway yes, I am willing to try, I have been looking for a way to play online for a long time. Tell me what I need to download and I'll do it.

**Comment by emanuelect** [comment]
I think it's a problem with this router I'm using anyway, as soon as I can I'll try process explorer with the home router.

**Comment by emanuelect** [comment]
I have just returned home, also here it does not tick no port on process explorer.

**Comment by zZeck** [comment]
Working on logging version now.
By the way, out of curiosity, did you find my patch through the rayman pirate community post?

**Comment by emanuelect** [comment]
No, I was randomly searching for the thousandth time on github XD

**Comment by zZeck** [comment]
Nice. I worked on this thing off and on for like a month, and was amazed anybody played the game.

**Comment by emanuelect** [comment]
I actually think a lot of people would play it if it worked. In 2015 on pirate community people were playing it with evolve, but then it closed.

**Comment by zZeck** [comment]
Do you have [HxD](https://mh-nexus.de/en/hxd/)?

What do the chunks of memory around 0x0C14E0 and 0xC1380 look like in your exe?

ctrl+g will let you jump to an offset in HxD

The exe I developed with was the 4:3 one from [this](https://www.mediafire.com/file/88tmdlj6hgd9ehu/Rayman_Arena_EXE_Widescreen_Fix.7z/file) archived linked to on the [pcwiki](https://www.pcgamingwiki.com/wiki/Rayman_M#Widescreen_resolution) page

**Comment by emanuelect** [comment]
![](https://cdn.discordapp.com/attachments/334474004263862273/876578210362572800/unknown.png)

**Comment by emanuelect** [comment]
The exe is the original one, but I changed the resolution today with the rayman control panel and it started in 16:9

**Comment by zZeck** [comment]
Well this looks like it's the same hex. The resolution patch should not matter.

**Comment by zZeck** [comment]
https://github.com/zZeck/RaymanArenaPatch/releases/tag/logs

Just added a couple of logs. The logs will look a bit weird because of some unicode string stuff I haven't fixed yet.

**Comment by zZeck** [comment]
What does the output of ipconfig command look like for you?

**Comment by emanuelect** [comment]
![image](https://user-images.githubusercontent.com/43710721/129494145-56c26623-8ec6-443e-8955-4af64997895d.png)
I'm not using hamachi anymore because today it decided to stop working for no reason, I try to go online and it disables the network driver, so I'm using radmin for now.

**Comment by emanuelect** [comment]
Probably that second router I was using away from home, caused me some problems with hamachi.

**Comment by zZeck** [comment]
If you select ethernet, and have procexp open on the side, when you try to create a game, does the TCP/IP tab show an attempt to bind to a port briefly?

**Comment by emanuelect** [comment]
no, nothing ever appears.

**Comment by zZeck** [comment]
in HxD, there is a chip icon that says "open main memory" (shift ctrl m)
If you open R_Arena.exe and goto 0x4C1370 what do you see?

**Comment by zZeck** [comment]
After the patch has been applied that is, in the menus or something would be fine.

**Comment by emanuelect** [comment]
![image](https://user-images.githubusercontent.com/43710721/129494565-4b801703-e9a6-47aa-a7e4-8a0898f1abc9.png)

**Comment by zZeck** [comment]
Alright. Now we're getting somewhere. That looks strange to me.

0x4C13B6 & 0x4C1556 have
64 00 6d 00
which is IP addr
100.0.109.0

0x4C155B is the netmask
and it has FF FF FF FF
255.255.255.255

that doesn't match anything in the ipconfig

now I need to figure out why.

**Comment by zZeck** [comment]
If that was the result for Ethernet, what do those bytes look like if you pick the VPN?

**Comment by emanuelect** [comment]
![image](https://user-images.githubusercontent.com/43710721/129494889-305b4c55-550c-4f73-9b6a-7c3a425a2e1b.png)

**Comment by zZeck** [comment]
I'm going to have to add some detailed logging for the IP_ADAPTER_ADDRESSES returned from GetAdaptersAddresses. Somehow, the information being read from it and patched in is not as expected.

That will take me a bit. Hopefully tomorrow I'll have something.

**Comment by emanuelect** [comment]
Great, thanks again for the mod,  If you need any more information, contact me.

**Comment by zZeck** [comment]
Try this [release](https://github.com/zZeck/RaymanArenaPatch/releases/tag/fixedLog), and paste the log.txt content here.

Should look something like

Before Adapter Select Creation
Before GetAdaptersAddresses call
Friendly Name: Hamachi
Physical Address: 7a 79 19 b 98 e3 0 0
Physical Address Length: 6
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
Friendly Name: Ethernet
Physical Address: 30 9c 23 9d 51 15 0 0
Physical Address Length: 6
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
Friendly Name: Loopback Pseudo-Interface 1
Physical Address: 0 0 0 0 0 0 0 0
Physical Address Length: 0
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------

**Comment by emanuelect** [comment]
Before Adapter Select Creation
Before GetAdaptersAddresses call
Friendly Name: Radmin VPN
Physical Address: 2 50 85 68 d b5 0 0
Physical Address Length: 6
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
Friendly Name: Hamachi
Physical Address: 7a 79 19 1 3c 4a 0 0
Physical Address Length: 6
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
Friendly Name: Ethernet
Physical Address: bc 5f f4 bf 4a b6 0 0
Physical Address Length: 6
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
Friendly Name: Loopback Pseudo-Interface 1
Physical Address: 0 0 0 0 0 0 0 0
Physical Address Length: 0
Ipv4 Enabled: 1
Ipv6 Enabled: 1
------
The game froze when I clicked on the create button

**Comment by mateusz-bartosiak** [comment]
I'm facing the same issue. Had to remove Virtualbox card adapter for the initial network card dialog to show. Now after choosing any card the game freezes on create. I'm running it on Windows 10 Home 20H2, installed via RCP, using widescreen fix exe to run it.

**Comment by zZeck** [comment]
Fixed hopefully. Was accessing ip address completely incorrect way that happened to work on machines tested somehow.

Try [this](https://github.com/zZeck/RaymanArenaPatch/releases/tag/ipAddressFix)

**Comment by zZeck** [comment]
Still not sure why those other adapters cause a crash. I have virtualbox on my machine and do not have a problem with those adapters being enabled.

**Comment by emanuelect** [comment]
With hamachi I got an error message when trying to create the room, but with radmin vpn it worked.
![image](https://user-images.githubusercontent.com/43710721/129648338-98f0b97f-ef6b-447e-9738-cc4998f1a60c.png)

**Comment by zZeck** [comment]
Great! Thanks for going back and forth with me on this.

What was the message? What does procexp and those areas in HxD look like for hamachi?

**Comment by emanuelect** [comment]
When I said error, I was talking about the game not being able to create the room with hamachi. Anyway today i started the pc to send you the hxd screens, but a strange thing is happening. If I select hamachi the game doesn't start, if I select radmin instead it starts normally.

**Comment by zZeck** [comment]
I was accessing the list of adapters incorrectly, and the buffer I was allocating for adapters was not large enough.

[This fix](https://github.com/zZeck/RaymanArenaPatch/releases/tag/1.2) should work no matter how many adapters you have, and every adapter should work.


@mat-io  how did you find the patch? searched randomly for it?

**Comment by emanuelect** [comment]
Ok, Hamachi now works perfectly
![image](https://user-images.githubusercontent.com/43710721/129824450-cf3eca93-4688-4a8f-99f9-fdabcee63800.png)
![image](https://user-images.githubusercontent.com/43710721/129824542-f9e785c9-2d80-4ea1-be76-44335c96246d.png)
The adapters are also displayed correctly now.
![image](https://user-images.githubusercontent.com/43710721/129824864-5625a4da-6bdc-4ab3-9125-edf818961e10.png)
However I played all evening with the previous version without any problem, in my opinion you should create a link to the patch in the Pcgamingwiki page of Rayman Arena.

**Comment by zZeck** [comment]
Hadn't thought of linking it there. So glad it is working. I have a lot of fond memories of this game.

I need to get my controller setup on PC if people actually are interested in playing.

If you're on the pirate community, maybe DM me and we could play sometime if you want. I'm zZeckHeck there.

**Comment by emanuelect** [comment]
Thanks, I think it will be difficult to play together because of the schedule, I am Italian and being on vacation these days I slept less and played more. However I try to share the mod in the discord server of rayman community pirate
