### ISSUE TITLE
dinput8.dll and therefore replace more controller

### ISSUE THREAD

**Issue by justaxe** [zZeck/RaymanArenaPatch#2]
hi zZeck congratulations on your patch for Rayman Arena, it works great with me.
Only I have a little problem when I want to play with the controller ...
I normally use a mod dll file to allow the game to detect my controller. But since I replaced the dll with yours, the game no longer recognizes it ...
Is it possible to integrate this dll into yours to be able to play in networks directly with the controller?

**Comment by zZeck** [comment]
Hello! Out of curiosity, is the input mod the input fix linked to on the [pcgamingwiki page](https://www.pcgamingwiki.com/wiki/Rayman_M#Input)?

Asi Loader supports dlls [other than dinput8](https://github.com/ThirteenAG/Ultimate-ASI-Loader#description). Try dsound.dll or ddraw.dll as the loader for my patch and it should solve your problem I think.

I will change my readme to mention people may want to use dsound or ddraw if they are using the controller fix.

**Comment by justaxe** [comment]
great thank you indeed it works by changing the name of the dll.
I call them "winmm.dll".
Do not rename it "dsound.dll" because otherwise there is no sound in the game. And "ddraw.dll" will prevent Voodoo from running.
Currently I have not noticed any issues with winmm.dll

for the entry mode it is about a dll which is generated by the software "rayman control panel" when one selects "enabled controller".
I don't know if it's the same as on the wiki

**Comment by zZeck** [comment]
To be clear, you should not have to rename my patch from arenapatch.asi.  My patch goes into Rayman Arena/plugins. You select the dll you want to use from the [Ultimate Asi Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/v4.61) package, and place that loader dll in the Rayman Arena directory. The Ultimate Asi Loader dll will load my patch from the plugins directory.  The asi loader dlls forward calls onto the real dll for the dll it replaces, so the program still works as before. That way you can replace dsound.dll for example with the Ultimate Asi Loader dsound.dll and the sound still works. The loader code just runs too.

**Comment by justaxe** [comment]
![image](https://user-images.githubusercontent.com/92937731/138569694-61ae4e3c-ab81-45cc-bda7-d8b657e9ad80.png)

this is how my game folder is configured.

So the dll that lets you run the patch causes the game to ignore the real windows dll when you start it, doesn't it?
